# This file contains the libraries that are used in the R juptyer notebooks to facilitate reproducibility using the renv package.
# Include required libraries here so that renv knows they are required, as it does not detect library() calls in ipynb files.

library(jsonlite)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(lubridate)
library(GGally)
library(stringr)
library(ggExtra)
library(readr)
library(purrr)
library(tibble)
library(jsonlite)
library(KEGGREST)
library(circlize)
library(pathview)
library(grid)
library(fs)
library(digest)
library(httr)
library(stats)
library(ape)
library(hash)
library(data.table)
library(rtracklayer)
library(gridExtra)
library(pheatmap)
library(rjson)