# This workflow will check all the links in the markdown files in the repository on Mondays at 4am UTC.

name: Check links on schedule
# https://github.com/lycheeverse/lychee-action

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 4 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --retry-wait-time 10 './**/*.md'
          

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
