# This workflow will check all the links in the markdown files in the repository whenever a push event occurs.

name: Check links on push
on: [ push ]
jobs:
  linkChecker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Link Checker
          # Reference: https://github.com/lycheeverse/lychee-action
          id: lychee
          uses: lycheeverse/lychee-action@v1