# This workflow will check all the links in the markdown files in the repository on Mondays at 4am UTC.

name: Check links on schedule
# https://github.com/lycheeverse/lychee-action

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 4 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --retry-wait-time 10 './**/*.md'
          

      - name: Get CODEOWNERS assignees
        if: env.lychee_exit_code != 0
        id: codeowners
        run: |
          owners=$(grep '^\*' .github/CODEOWNERS | sed 's/^\*[[:space:]]*//' | sed 's/@//g' | tr -s ' ' ',' | sed 's/,$//')
          echo "assignees=$owners" >> $GITHUB_OUTPUT

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6.0.0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          assignees: ${{ steps.codeowners.outputs.assignees }}
