name: Execute notebook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v2

    - id: setup-python
      name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - id: python-deps
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install jupyter

    - id: execute-notebook
      name: Execute notebook
      run: |
        jupyter nbconvert --execute --to notebook --inplace bioscales_biogeochemical_metadata/python/bioscales.ipynb